#!/bin/bash

branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$branch" == "develop" || "$branch" == "master" ]]; then
  echo "❌ Está prohibido hacer push directamente a '$branch'."
  echo "✅ Crea una rama y usa pull request si es necesario."
  exit 1
fi