#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Generates and copy to the clipboard a random password
#?? 1.0.0
##?
##? Usage:
##?   random_password
docs::parse "$@"

random_pwd=$(dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 | rev | cut -b 2- | rev)
echo -n $random_pwd | pbcopy
echo $random_pwd

osascript -e 'display notification "'"$random_pwd"'" with title "Random Password copied to the clipboard"'